// Database types for Supabase
// This file will be regenerated by `supabase gen types typescript` after migrations

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[];

export type OrgMemberRole = "org_admin" | "user" | "staff";
export type OrgMemberStatus = "active" | "invited" | "suspended" | "removed";
export type TicketType =
    | "turnover_cleaning"
    | "routine_cleaning"
    | "restock"
    | "maintenance"
    | "inspection"
    | "custom";
export type TicketPriority = "low" | "medium" | "high" | "urgent";
export type TicketStatus =
    | "created"
    | "assigned"
    | "accepted"
    | "in_progress"
    | "completed"
    | "cancelled";
export type BundleScope = "admin_global" | "user_private";
export type TriggerType = "booking_end" | "daily" | "weekly" | "custom";
export type BookingStatus = "confirmed" | "cancelled";
export type EntryMethod = "keypad" | "keybox" | "doorman" | "host_meet" | "other";
export type ItemLineStatus =
    | "needed"
    | "shortage"
    | "reserved"
    | "picked"
    | "consumed"
    | "returned";
export type InventoryTransactionType =
    | "stock_in"
    | "reserve"
    | "release"
    | "deduct"
    | "adjust";
export type DSARType = "export" | "delete";
export type DSARStatus = "requested" | "in_review" | "completed" | "rejected";
export type SubstitutionStatus = "requested" | "approved" | "rejected";

export interface Database {
    public: {
        Tables: {
            orgs: {
                Row: {
                    id: string;
                    name: string;
                    settings: Json;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    name: string;
                    settings?: Json;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    name?: string;
                    settings?: Json;
                    created_at?: string;
                };
            };
            org_members: {
                Row: {
                    org_id: string;
                    user_id: string;
                    role: OrgMemberRole;
                    status: OrgMemberStatus;
                    created_at: string;
                };
                Insert: {
                    org_id: string;
                    user_id: string;
                    role: OrgMemberRole;
                    status?: OrgMemberStatus;
                    created_at?: string;
                };
                Update: {
                    org_id?: string;
                    user_id?: string;
                    role?: OrgMemberRole;
                    status?: OrgMemberStatus;
                    created_at?: string;
                };
            };
            platform_admins: {
                Row: {
                    user_id: string;
                };
                Insert: {
                    user_id: string;
                };
                Update: {
                    user_id?: string;
                };
            };
            profiles: {
                Row: {
                    user_id: string;
                    full_name: string | null;
                    phone: string | null;
                    created_at: string;
                };
                Insert: {
                    user_id: string;
                    full_name?: string | null;
                    phone?: string | null;
                    created_at?: string;
                };
                Update: {
                    user_id?: string;
                    full_name?: string | null;
                    phone?: string | null;
                    created_at?: string;
                };
            };
            staff_profiles: {
                Row: {
                    user_id: string;
                    org_id: string;
                    skills: string[];
                    home_warehouse_id: string | null;
                    created_at: string;
                };
                Insert: {
                    user_id: string;
                    org_id: string;
                    skills?: string[];
                    home_warehouse_id?: string | null;
                    created_at?: string;
                };
                Update: {
                    user_id?: string;
                    org_id?: string;
                    skills?: string[];
                    home_warehouse_id?: string | null;
                    created_at?: string;
                };
            };
            properties: {
                Row: {
                    id: string;
                    org_id: string;
                    owner_user_id: string;
                    name: string;
                    address: string;
                    lat: number;
                    lng: number;
                    timezone: string;
                    service_warehouse_id: string | null;
                    turnover_package_id: string | null;
                    access_notes: string;
                    entry_method: EntryMethod;
                    entry_details_encrypted: string | null;
                    emergency_contact: Json;
                    ical_url_encrypted: string | null;
                    ical_meta: Json | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    org_id: string;
                    owner_user_id: string;
                    name: string;
                    address: string;
                    lat: number;
                    lng: number;
                    timezone?: string;
                    service_warehouse_id?: string | null;
                    turnover_package_id?: string | null;
                    access_notes?: string;
                    entry_method?: EntryMethod;
                    entry_details_encrypted?: string | null;
                    emergency_contact?: Json;
                    ical_url_encrypted?: string | null;
                    ical_meta?: Json | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    org_id?: string;
                    owner_user_id?: string;
                    name?: string;
                    address?: string;
                    lat?: number;
                    lng?: number;
                    timezone?: string;
                    service_warehouse_id?: string | null;
                    turnover_package_id?: string | null;
                    access_notes?: string;
                    entry_method?: EntryMethod;
                    entry_details_encrypted?: string | null;
                    emergency_contact?: Json;
                    ical_url_encrypted?: string | null;
                    ical_meta?: Json | null;
                    created_at?: string;
                };
            };
            bookings: {
                Row: {
                    id: string;
                    org_id: string;
                    property_id: string;
                    source: string;
                    uid: string;
                    start_at: string;
                    end_at: string;
                    status: BookingStatus;
                    last_modified: string | null;
                    sequence: number | null;
                    raw_hash: string;
                    raw_payload: Json;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    org_id: string;
                    property_id: string;
                    source?: string;
                    uid: string;
                    start_at: string;
                    end_at: string;
                    status?: BookingStatus;
                    last_modified?: string | null;
                    sequence?: number | null;
                    raw_hash: string;
                    raw_payload?: Json;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    org_id?: string;
                    property_id?: string;
                    source?: string;
                    uid?: string;
                    start_at?: string;
                    end_at?: string;
                    status?: BookingStatus;
                    last_modified?: string | null;
                    sequence?: number | null;
                    raw_hash?: string;
                    raw_payload?: Json;
                    created_at?: string;
                };
            };
            tickets: {
                Row: {
                    id: string;
                    org_id: string;
                    property_id: string;
                    created_by: string;
                    assigned_to: string | null;
                    title: string;
                    description: string;
                    type: TicketType;
                    tags: string[];
                    priority: TicketPriority;
                    due_at: string | null;
                    status: TicketStatus;
                    bundles_applied: string[];
                    checklist: Json;
                    created_at: string;
                    updated_at: string;
                    archived_at: string | null;
                };
                Insert: {
                    id?: string;
                    org_id: string;
                    property_id: string;
                    created_by: string;
                    assigned_to?: string | null;
                    title: string;
                    description?: string;
                    type: TicketType;
                    tags?: string[];
                    priority?: TicketPriority;
                    due_at?: string | null;
                    status?: TicketStatus;
                    bundles_applied?: string[];
                    checklist?: Json;
                    created_at?: string;
                    updated_at?: string;
                    archived_at?: string | null;
                };
                Update: {
                    id?: string;
                    org_id?: string;
                    property_id?: string;
                    created_by?: string;
                    assigned_to?: string | null;
                    title?: string;
                    description?: string;
                    type?: TicketType;
                    tags?: string[];
                    priority?: TicketPriority;
                    due_at?: string | null;
                    status?: TicketStatus;
                    bundles_applied?: string[];
                    checklist?: Json;
                    created_at?: string;
                    updated_at?: string;
                    archived_at?: string | null;
                };
            };
            bundles: {
                Row: {
                    id: string;
                    org_id: string;
                    scope: BundleScope;
                    owner_user_id: string | null;
                    name: string;
                    description: string;
                    items: Json;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    org_id: string;
                    scope: BundleScope;
                    owner_user_id?: string | null;
                    name: string;
                    description?: string;
                    items: Json;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    org_id?: string;
                    scope?: BundleScope;
                    owner_user_id?: string | null;
                    name?: string;
                    description?: string;
                    items?: Json;
                    created_at?: string;
                };
            };
            packages: {
                Row: {
                    id: string;
                    org_id: string;
                    property_id: string | null;
                    name: string;
                    description: string;
                    trigger_type: TriggerType;
                    trigger_rules: Json;
                    bundle_ids: string[];
                    checklist: Json;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    org_id: string;
                    property_id?: string | null;
                    name: string;
                    description?: string;
                    trigger_type: TriggerType;
                    trigger_rules: Json;
                    bundle_ids?: string[];
                    checklist?: Json;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    org_id?: string;
                    property_id?: string | null;
                    name?: string;
                    description?: string;
                    trigger_type?: TriggerType;
                    trigger_rules?: Json;
                    bundle_ids?: string[];
                    checklist?: Json;
                    created_at?: string;
                };
            };
            warehouses: {
                Row: {
                    id: string;
                    org_id: string;
                    name: string;
                    address: string;
                    lat: number;
                    lng: number;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    org_id: string;
                    name: string;
                    address: string;
                    lat: number;
                    lng: number;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    org_id?: string;
                    name?: string;
                    address?: string;
                    lat?: number;
                    lng?: number;
                    created_at?: string;
                };
            };
            inventory_skus: {
                Row: {
                    id: string;
                    org_id: string;
                    sku_code: string;
                    name: string;
                    unit: string;
                    min_stock: number;
                    reorder_level: number;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    org_id: string;
                    sku_code: string;
                    name: string;
                    unit: string;
                    min_stock?: number;
                    reorder_level?: number;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    org_id?: string;
                    sku_code?: string;
                    name?: string;
                    unit?: string;
                    min_stock?: number;
                    reorder_level?: number;
                    created_at?: string;
                };
            };
            subscriptions: {
                Row: {
                    id: string;
                    org_id: string;
                    user_id: string;
                    stripe_customer_id: string;
                    stripe_subscription_id: string;
                    plan: string;
                    status: string;
                    current_period_end: string;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    org_id: string;
                    user_id: string;
                    stripe_customer_id: string;
                    stripe_subscription_id: string;
                    plan: string;
                    status: string;
                    current_period_end: string;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    org_id?: string;
                    user_id?: string;
                    stripe_customer_id?: string;
                    stripe_subscription_id?: string;
                    plan?: string;
                    status?: string;
                    current_period_end?: string;
                    created_at?: string;
                };
            };
        };
        Views: Record<string, never>;
        Functions: Record<string, never>;
        Enums: {
            org_member_role: OrgMemberRole;
            org_member_status: OrgMemberStatus;
            ticket_type: TicketType;
            ticket_priority: TicketPriority;
            ticket_status: TicketStatus;
            bundle_scope: BundleScope;
            trigger_type: TriggerType;
            booking_status: BookingStatus;
            entry_method: EntryMethod;
        };
    };
}
